name: flutter_speed_dial_material_design
description: Flutter plugin to implement a Material Design Speed Dial (https://material.io/components/buttons-floating-action-button/#types-of-transitions)
version: 2.0.0
homepage: https://github.com/fysoul17/flutter_speed_dial_material_design

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
